apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: data
spec:
    storageClassName: rook-block
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 100Gi
